In [64]:
import tensorflow as tf
from tensorflow import keras
from keras.datasets import imdb

In [65]:
from keras import models
from keras import layers

In [66]:
model = models.Sequential([
    layers.Input(shape=(1,)),  # Każda próbka to pojedyncza liczba
    layers.Dense(1)            # Właściwa warstwa obliczeniowa - wyrzuca jedna liczbe 
])

In [67]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [68]:
# uzywamy tu wzoru y = w*x + b

In [69]:
# mamy tutaj dwa parametry w - wage i b - wyraz wolny

In [70]:
w, b = model.get_weights()
print("Waga w:", w)
print("Bias b:", b)

Waga w: [[1.5592457]]
Bias b: [0.]


# zadanie 2 

In [71]:
# y = 2x + 1
# mamy odkryc ze waga to 2 a wyraz wolny to 1 

In [72]:
import numpy as np

x = np.array([-5, -2, 0, 1, 2, 3, 4], dtype=float)
y = np.array([-9, -3, 1, 3, 5, 7, 9], dtype=float)

In [73]:
model = models.Sequential([
    layers.Input(shape=(1,)),  
    layers.Dense(1)             
])

In [74]:
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.1),
    loss='mse')

In [75]:
from keras import optimizers

In [76]:
history = model.fit(x,
                    y,
                    epochs = 500,
                    verbose=0)

In [77]:
w, b = model.get_weights()

In [78]:
w

array([[1.9999998]], dtype=float32)

In [79]:
b

array([1.0000001], dtype=float32)

In [80]:
model.predict(np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([[20.999998]], dtype=float32)

In [81]:
model.predict(np.array([20.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


array([[40.999996]], dtype=float32)

In [82]:
model.predict(np.array([-5.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[-8.999999]], dtype=float32)

In [83]:
loss_function_1 = history.history['loss'][-1]

# zadanie 3 

In [84]:
model_2= models.Sequential([
    layers.Input(shape=(1,)),  
    layers.Dense(4, activation='relu'),
    layers.Dense(1)             
])

In [85]:
model_2.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.1),
    loss='mse')

In [86]:
history_2 = model_2.fit(x,
                    y,
                    epochs = 500,
                    verbose=0)

In [87]:
w1, b1, w2, b2 = model_2.get_weights()

In [88]:
w1, w2

(array([[-0.56710154, -0.71980894,  1.6002679 , -0.97075194]],
       dtype=float32),
 array([[-0.4039638 ],
        [-1.2314259 ],
        [ 1.249789  ],
        [-0.91117287]], dtype=float32))

In [89]:
b1, b2

(array([-5.0543594e-01,  9.9045255e-06,  1.6335709e-01,  2.0143364e-07],
       dtype=float32),
 array([0.7958455], dtype=float32))

In [90]:
model_2.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 4)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41 (168.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 28 (116.00 B)

In [91]:
model_2.predict(np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[20.999977]], dtype=float32)

In [92]:
model_2.predict(np.array([-5.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[-9.000002]], dtype=float32)

In [93]:
loss_function_2 = history_2.history['loss'][-1]

In [94]:
# dolozenie warstwy nic nie dalo bo blad na obu jest praktycznie zerowy, dodatkowo relu zepsulo wartosci ujemne i model
# zle przewiduje wartosci minusowe

# zadanie 4

In [95]:
model_3= models.Sequential([
    layers.Input(shape=(1,)),  
    layers.Dense(8, activation='relu'),
    layers.Dense(8, activation='relu'),
    layers.Dense(1)             
])

In [96]:
# 1 warstwa waga polaczen 1 * 8 + 8(bias) razem 16
# 2 warstwa waga polaczen 8 * 8 + 8 = 72
# 3 warstwa waga polaczen 8 * 1 + 1 =9 razem 91 parametrow

In [97]:
model_3.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.1),
    loss='mse')

In [98]:
history_3 = model_3.fit(x,
                        y,
                        epochs=500,
                        verbose=0)

In [99]:
weights_3 = model_3.get_weights()

In [100]:
model_3.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_17 (Dense)                │ (None, 8)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 293 (1.15 KB)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 196 (788.00 B)

In [101]:
model_3.predict(np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[20.999998]], dtype=float32)

In [102]:
model_3.predict(np.array([-5.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[-8.999999]], dtype=float32)

In [103]:
loss_function_3 = history_3.history['loss'][-1]

In [104]:
# porownianie loss function zad 2 vs 3 vs 4

In [105]:
print(f"""zad 2 loss function: {loss_function_1}, params = {model.count_params()}
zad 3 loss function: {loss_function_2}, params = {model_2.count_params()}
zad 4 loss function: {loss_function_3}, params = {model_3.count_params()}
""")

zad 2 loss function: 4.567774652443346e-13, params = 2
zad 3 loss function: 1.5398475897154817e-11, params = 13
zad 4 loss function: 2.030122192925245e-15, params = 97



In [106]:
# 4.24 ma najmniejsza strate

In [108]:
# wybieramyt model z 2 poniewaz jest najlatwiejszy i zuzywaa najmniej ramu

 czy głębsza sieć nauczyła się lepiej? Jeśli nie — dlaczego dokładanie warstw nic tu nie daje?

# zadanie 5 

zaleznosc y = x²

In [189]:
x = np.arange(-10, 11, dtype=float)
y = x**2

In [190]:
model_4 = models.Sequential([
    layers.Input(shape=(1,)),  
    layers.Dense(1)             
])

In [191]:
model_4.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='mse')
# optymalne 0.001 learning rate dla adama

In [192]:
history_4 = model_4.fit(x, y, epochs=500, verbose=0)

In [193]:
model_4.summary()

Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_31 (Dense)                │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8 (36.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 6 (28.00 B)

In [194]:
model_4.get_weights()

[array([[-0.23928553]], dtype=float32), array([0.49850515], dtype=float32)]

In [195]:
model_4.predict(np.array([-5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[1.6949327]], dtype=float32)

In [196]:
model_4.predict(np.array([5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[-0.69792247]], dtype=float32)

In [202]:
# y = -0.23 * -5 + 0,49 = -0.69

In [198]:
model_4.predict(np.array([2]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[0.01993409]], dtype=float32)

In [199]:
model_4.predict(np.array([3]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[-0.21935144]], dtype=float32)

In [200]:
loss_function_x2_1 = history_4.history['loss'][-1]

In [201]:
# ten model nigdy nie zadziala poniewz ma wzor liniowy - y = activation(wx +b)

# zadanie 6

In [241]:
tf.keras.utils.set_random_seed(42)
model_5 = models.Sequential([
    layers.Input(shape=(1,)),  
    layers.Dense(16, activation='relu'),
    layers.Dense(1)
])

In [242]:
tf.keras.utils.set_random_seed(42)
model_6 = models.Sequential([
    layers.Input(shape=(1,)),  
    layers.Dense(16, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(1)
])

In [243]:
model_5.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.01),
    loss='mse')

In [244]:
model_6.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.01),
    loss='mse')

In [245]:
history_5 = model_5.fit(x, y, epochs=500, verbose=0)

In [246]:
loss_function_x2_2 = history_5.history['loss'][-1]

In [247]:
model_5.predict(np.array([5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


array([[35.539112]], dtype=float32)

In [248]:
history_6 = model_6.fit(x, y, epochs=500, verbose=0)

In [249]:
loss_function_x2_3 = history_6.history['loss'][-1]

In [250]:
model_6.predict(np.array([5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[24.588152]], dtype=float32)

In [251]:
model_5.summary()

Model: "sequential_22"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_42 (Dense)                │ (None, 16)             │            32 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_43 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 149 (600.00 B)

 Trainable params: 49 (196.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 100 (404.00 B)

In [252]:
model_6.summary()

Model: "sequential_23"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_44 (Dense)                │ (None, 16)             │            32 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_45 (Dense)                │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_46 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 965 (3.77 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 644 (2.52 KB)

In [254]:
print(f"""przyklad 1 loss function: {loss_function_x2_1}, params = {model_4.count_params()}
przyklad 2 loss function: {loss_function_x2_2}, params = {model_5.count_params()}
przyklad 3 loss function: {loss_function_x2_3}, params = {model_6.count_params()}
""")

przyklad 1 loss function: 2378.539794921875, params = 2
przyklad 2 loss function: 61.43419647216797, params = 49
przyklad 3 loss function: 1.5677118301391602, params = 321



In [ ]:
# jesli mamy dane nieliniowe dodawanie wartosci 

# Dokładanie warstw i neuronów pomaga wtedy, gdy dane zawierają nieliniowe zależności lub hierarchiczne wzorce, a staje się marnotrawstwem, gdy problem jest liniowy, zbiór danych zbyt mały lub model osiągnął już zbieżność