In [1]:
import tensorflow as tf
from tensorflow import keras
from keras.datasets import imdb

In [2]:
from keras import models
from keras import layers

In [14]:
model = models.Sequential([
    layers.Input(shape=(1,)),  # Każda próbka to pojedyncza liczba
    layers.Dense(1)            # Właściwa warstwa obliczeniowa - wyrzuca jedna liczbe 
])

In [15]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# uzywamy tu wzoru y = w*x + b

In [16]:
# mamy tutaj dwa parametry w - wage i b - wyraz wolny

In [17]:
w, b = model.get_weights()
print("Waga w:", w)
print("Bias b:", b)

Waga w: [[-0.8768076]]
Bias b: [0.]


# zadanie 2 

In [88]:
# y = 2x + 1
# mamy odkryc ze waga to 2 a wyraz wolny to 1 

In [89]:
import numpy as np

x = np.array([0, 1, 2, 3, 4], dtype=float)
y = np.array([1, 3, 5, 7, 9], dtype=float)

In [90]:
model = models.Sequential([
    layers.Input(shape=(1,)),  
    layers.Dense(1)             
])

In [91]:
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.1),
    loss='mse')

In [92]:
from keras import optimizers

In [93]:
history = model.fit(x,
                    y,
                    epochs = 500,
                    verbose=0)

In [94]:
w, b = model.get_weights()

In [95]:
w

array([[2.0000007]], dtype=float32)

In [96]:
b

array([0.9999986], dtype=float32)

In [97]:
model.predict(np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[21.000006]], dtype=float32)

In [98]:
model.predict(np.array([20.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[41.000015]], dtype=float32)

In [100]:
model.predict(np.array([-5.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[-9.000005]], dtype=float32)

In [112]:
history.history['loss'][-1]

1.2512658010416233e-12

# zadanie 3 

In [113]:
model_2= models.Sequential([
    layers.Input(shape=(1,)),  
    layers.Dense(4, activation='relu'),
    layers.Dense(1)             
])

In [114]:
model_2.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.1),
    loss='mse')

In [115]:
history_2 = model_2.fit(x,
                    y,
                    epochs = 500,
                    verbose=0)

In [116]:
w1, b1, w2, b2 = model_2.get_weights()

In [117]:
w1, w2

(array([[-0.1551301 , -0.92943376,  1.27742   ,  0.7607269 ]],
       dtype=float32),
 array([[ 0.7374432 ],
        [-0.84122264],
        [ 1.0419662 ],
        [ 0.8793878 ]], dtype=float32))

In [118]:
b1, b2

(array([-1.2476317e+00,  0.0000000e+00,  1.0335176e-01, -1.5779229e-05],
       dtype=float32),
 array([0.89231706], dtype=float32))

In [119]:
model_2.predict(np.array([10.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[21.000017]], dtype=float32)

In [120]:
model_2.predict(np.array([-5.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[-3.0169864]], dtype=float32)

In [121]:
history_2.history['loss'][-1]

1.7882939920554897e-11

In [122]:
# dolozenie warstwy nic nie dalo bo blad na obu jest praktycznie zerowy, dodatkowo relu zepsulo wartosci ujemne i model
# zle przewiduje wartosci minusowe